stages:
  stage_01:
    cmd: python stage_01.py
    # Stage 1, file to start execution with 
    deps:
    # dependencies noted here
      - stage_01.py
    outs:
    # output files noted here
      - artifacts01.txt

  stage_02:
    cmd: python stage_02.py
    # Stage 2, file to start execution with     
    deps:
    # dependencies noted here
      - stage_02.py
      - artifacts01.txt

  stage_03:
    cmd: python stage_03.py
    # Stage 2, file to start execution with     
    deps:
    # dependencies noted here
      - stage_03.py
      - artifacts01.txt
    outs:
    # output files noted here
      - artifacts02.txt